### ISSUE TITLE
API Key Required?

### ISSUE THREAD

**Issue by daveachuk** [rainlab/location-plugin#18]
Not sure why no one else is (apparently) having this issue, but the geocoding address lookup function does not work unless you include the Google Maps API Key in the javascript include.

$this->addJs('//maps.googleapis.com/maps/api/js?libraries=places&key=[YOUR_API_KEY]');

I wonder if I am just being asked for an API key for unknown reasons and no one else is? Perhaps a policy update at Google? If it's happening to everyone perhaps I or someone else can add the needed settings functionality to prevent people from having to change the source.

**Comment by daftspunk** [comment]
I thought the error message was just a warning...

**Comment by daveachuk** [comment]
Yeah, I couldn't get it to work without the API Key -- the box would become deactivated and have a red X over it. Maybe Google doesn't like my IP? Will wait for confirmation from others before doing anything about it!

**Comment by daftspunk** [comment]
It would appear there has been a recent change: https://www.igorkromin.net/index.php/2016/06/24/google-maps-now-forcing-developers-to-use-an-api-key-returning-missingkeymaperror/

It went unnoticed because existing URLs are not affected, clever Google. So we will need to add Location settings where an API key can be defined, also documentation is needed on how to generate one.
