### ISSUE TITLE
Cannot install due to the already present "company" field in users table ...

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/location-plugin#27]
... installed with Rainlab:UserPlus plugin, which is working fine, and was already installed on the system.

**Comment by dshoreman** [comment]
What error(s) are you getting? The location plugin doesn't extend the User plugin at all.

Does the UserPlus plugin add countries and states, too? The only thing I can see possibly being an issue is Location checks for a `rainlab_user_countries` table and renames it to `rainlab_location_countries` (because countries used to be part of the User plugin). Same for `rainlab_user_states`, but if UserPlus doesn't use those tables then it shouldn't be an issue.

**Comment by WebShapedBiz** [comment]
> "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'company' (SQL: alter table `users` add `phone` varchar(100) null, add `company` varchar(100) null, add `street_addr` varchar(255) null, add `city` varchar(100) null, add `zip` varchar(20) null)" on line 662 of /home/webshape/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by WebShapedBiz** [comment]
There is a User Profile plugin which enables you to add custom fields to `user` table and I was using it before adding the company field. I've checked and that field remained in the table after plugin removal.

So I believe that this problem is not related to your plugin directly but it would be useful for your plugin to check if any other plugin is adding things in the `user` table before executing it's SQL statements, since there is obviously more plugins capable to add fields in the aforementioned table.

I hope this helps.

Cheers.

**Comment by daftspunk** [comment]
Interesting, it would appear you have `company` but not `phone` so the check used is not working:

```
if (Schema::hasColumns('users', ['phone', 'company'])) {
```

I wonder how is this possible? As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
