### ISSUE TITLE
Extra country/state field

### ISSUE THREAD

**Issue by dathwa** [rainlab/location-plugin#75]
Hi.
I have the country and state fields set in my user table and the plugin works fine.
I want to add additional seasonal_country and seasonal_state fields to my user table (model extended) and edit as normal in the backend. Can you give me sime pointers? I can add them as relations OK, but i can't get the dependsOn functionality working for the state.
Thank-you.

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Slack: https://octobercms-slack.herokuapp.com/
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Forum: https://octobercms.com/forum
